# Generated by Django 6.0.1 on 2026-01-11 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('city', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObservationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='observation',
            name='date',
        ),
        migrations.AlterField(
            model_name='observation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='observations/'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='observation',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='dairy.observationday'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observation',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='observations', to='dairy.observationtag'),
        ),
    ]
