# Generated by Django 6.0.1 on 2026-01-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0002_observationday_observationtag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
