# Generated by Django 6.0.1 on 2026-01-11 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0003_alter_observation_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='day',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='created_at',
        ),
        migrations.AddField(
            model_name='observation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='CelestialObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='dairy.observation')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(default='Телескоп', max_length=50)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='dairy.observation')),
            ],
        ),
        migrations.DeleteModel(
            name='ObservationDay',
        ),
        migrations.DeleteModel(
            name='ObservationTag',
        ),
    ]
