# Generated by Django 6.0.1 on 2026-01-11 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0004_remove_observation_day_remove_observation_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelestialBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body_type', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='type',
        ),
        migrations.AddField(
            model_name='observation',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dairy.equipment'),
        ),
        migrations.AddField(
            model_name='observation',
            name='celestial_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dairy.celestialbody'),
        ),
        migrations.DeleteModel(
            name='CelestialObject',
        ),
    ]
